version: '3'
services:
  app:
    build: .
    ports:
      - "100:100"
    environment:
      - symbol=SUIUSDT
      - apiKey=pMk2SJcODJI7MYPmXq0pDsuhCUlT3Ev2VKbjanC21m27Htm7HWOSasaCH8OORrOi
      - secretKey=pPvanzVzxEivBH8bcyorX6ZnM9jMT2r5F06v0c0dba0c08wVKQyQ2lVduYqDHBqL
      - DbUrl=mongodb+srv://abdulSaboor:A.saboor18@cluster0.xnmzuzr.mongodb.net/
